name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"
      - name: Use pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
<<<<<<< HEAD
          version: "9.14.4"
=======
          version: "9.3.0"
>>>>>>> master
      - name: Install dependencies
        run: pnpm i
      # - name: Check
      #   run: pnpm run check
      - name: Test
        run: pnpm run test
